name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build

      - name: Run unit tests (ChromeHeadless)
        run: npm test -- --watch=false --browsers=ChromeHeadless

  versioning:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '6.0.0'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            const version = '${{ steps.gitversion.outputs.semVer }}';
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${version}`,
              sha: context.sha
            });

      - name: Create GitHub Release
        uses: actions/github-script@v5
        with:
          script: |
            const version = '${{ steps.gitversion.outputs.semVer }}';
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${version}`,
              name: `v${version}`,
              body: `Release for v${version}`,
              draft: false,
              prerelease: false
            });
