name: Set new version

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
     
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1
      with:
        versionSpec: '6.0.0'

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1

    - name: Create Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "v${{ steps.gitversion.outputs.semVer }}" -m "Tagging version v${{ steps.gitversion.outputs.semVer }}"
        git push origin "v${{ steps.gitversion.outputs.semVer }}"
